export const FETCH_OCCUPATIONS_LOADING = 'FETCH_OCCUPATIONS_LOADING';
export const FETCH_OCCUPATIONS_SUCCESS = 'FETCH_OCCUPATIONS_SUCCESS';
export const FETCH_OCCUPATIONS_FAILURE = 'FETCH_OCCUPATIONS_FAILURE';

